name: {{cookiecutter.project_name}}
channels:
  - defaults
dependencies:
  - pip
  - pre-commit
  - setuptools
  - pytest
  - cookiecutter
  - sphinx
  - jupyter
  - flake8
  - pathlib
  - python=3.8
  - ipykernel
